# Site settings

title: Craig Opie
description: 'Professional Portfolio'
url: 'https://craigopie.github.io'
baseurl: ''
profilepic: '/images/sm_portrait.png'
bkimage: '/images/backgroundalt.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'f13480f45a.js'

author:
  name: 'Craig Opie'
  email: opieca@hawaii.edu
  github_username:  CraigOpie
  linkedin_username:  craig-opie-90a98553

bio-page-label: Resume
theme-home: theme-home.html
theme-projects: theme-projects.html
theme-essays: theme-essays.html
theme-statements: theme-statements.html
theme-bio: theme-bio.html
rouge-theme: igorpro

destination: _site
markdown: kramdown
highlighter: rouge
include: [_data]

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  input: GFM
  hard_wrap: false

exclude: ['README.md', 'screenshot-overview.png']
