# Site settings
title: Craig Opie
description: 'Business Card Page'
url: 'http://craigopie.github.io'
baseurl: ''
profilepic: '/images/sm_portrait.png'
bkimage: '/images/backgroundalt.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'f13480f45a.js'

author:
  name: 'Craig Opie'
  email: craig@hawaii.edu
  github_username:  CraigOpie
  linkedin_username:  craig-opie-90a98553

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
